FROM debian:jessie

RUN apt-get update && apt-get upgrade -y -o Dpkg::Options::="--force-confnew" \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*  # 2016-06-01

RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
						curl \
						dnsutils \
						vim-tiny \
						lsof \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY feed-dns /

ENTRYPOINT ["/feed-dns"]
