FROM phusion/baseimage:0.9.19

RUN apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install --no-install-suggests --no-install-recommends -y \
        curl \
        dnsutils \
        vim-tiny \
        lsof \
    && apt-get clean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* /tmp/*

ENV NGINX_VERSION 1.10.1
ENV NGINX_SHA256 1fd35846566485e03c0e318989561c135c598323ff349c503a6c14826487a801
ENV VTS_VERSION 0.1.10
ENV VTS_SHA256 c6f3733e9ff84bfcdc6bfb07e1baf59e72c4e272f06964dd0ed3a1bdc93fa0ca

COPY build-nginx.sh /tmp
RUN /bin/bash /tmp/build-nginx.sh

COPY feed-ingress /
COPY nginx.tmpl /nginx/
RUN chown nginx:nginx /nginx/nginx.tmpl

ADD scripts/logrotate.config /etc/logrotate.d/nginx
RUN chmod 600 /etc/logrotate.d/nginx

ADD scripts/logrotate.cron /etc/cron.d/nginx
RUN chmod 600 /etc/cron.d/nginx

# Defer execution as the log dir may be mounted when running
ADD scripts/log-dir-ownership.sh /etc/my_init.d/log-dir-ownership.sh

ENTRYPOINT ["/sbin/my_init", "--quiet", "--", "/sbin/setuser", "nginx", \
    "/feed-ingress", "-nginx-workdir", "/nginx"]
