FROM phusion/baseimage:0.9.19

ENV NGINX_VERSION 1.10.1-1~xenial

RUN curl http://nginx.org/keys/nginx_signing.key > /tmp/nginx_signing.key \
    && apt-key add /tmp/nginx_signing.key \
    && rm -f /tmp/nginx_signing.key \
	&& echo "deb http://nginx.org/packages/ubuntu/ xenial nginx" >> /etc/apt/sources.list \
	&& apt-get upgrade -y -o Dpkg::Options::="--force-confnew" \
	&& apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
						ca-certificates \
						nginx=${NGINX_VERSION} \
						gettext-base \
						curl \
						dnsutils \
						vim-tiny \
						lsof \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* # 2016-07-13

WORKDIR /
COPY feed-ingress /

RUN mkdir /nginx
COPY nginx.tmpl /nginx/
RUN chown -R nginx:nginx /nginx

ENTRYPOINT ["/sbin/my_init", "--quiet", "--", "/sbin/setuser", "nginx", \
    "/feed-ingress", "-nginx-workdir", "/nginx"]
